version: '3' 
services: 
    db: 
        image: mariadb:10.5.3
        volumes: 
            - moodle_data:/var/lib/mysql 
        restart: always 
        environment: 
            MYSQL_ROOT_PASSWORD: m00dle 
            MYSQL_DATABASE: lms-moodle 
            MYSQL_USER: moodle 
            MYSQL_PASSWORD: m00dle 
        networks: 
            - moodle 
 
    app: 
        depends_on: 
            - db 
        image: mridho/lms-moodle:latest 
        ports: 
            - "80:80" 
        restart: always 
        networks: 
            - moodle 
 
volumes: 
    moodle_data: 
 
networks: 
    moodle:
